[package]
name = "rubiks-cube-rl-experiments"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33.2"
tobj = "4.0.3"
ahash = "0.8.12"
libc = "0.2"
tch = "0.20.0"
rand = "0.9.1"
log = "0.4.27"
simplelog = "0.12.2"
chrono = "0.4.41"